export const expenseInitialState = {
    expense: {
        id: 0,
        title: '',
        transaction_type: '',
        category: {
            id: 0,
            name: '',
            icon: '',
        },
        amount: 0,
        date: new Date().toISOString(),
        created_at: '',
        description: '',
        account: {
            id: 0,
            name: '',
            icon: '',
            balance: 0,
            description: '',
            account_type: '',
        },
        file_url: '',
    },
    expenseDetails: {
        id: 0,
        title: '',
        transaction_type: '',
        category: {
            id: 0,
            name: '',
            icon: '',
        },
        amount: 0,
        date: '',
        created_at: '',
        description: '',
        account: {
            id: 0,
            name: '',
            icon: '',
            balance: 0,
            description: '',
            account_type: '',
        },
        file_url: '',
    },
};
